CREATE TABLE IF NOT EXISTS Genre (
	Genre_ID SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL
);
CREATE TABLE IF NOT EXISTS Artist (
	Artist_ID SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL
);
CREATE TABLE IF NOT EXISTS Album (
	Album_ID SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	year INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS Compilation (
	Compilation_ID SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	year INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS Track (
	Track_ID SERIAL PRIMARY KEY,
	Album_ID INTEGER REFERENCES Album(Album_ID),
	name VARCHAR(40) NOT NULL,
	lenght INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS Genre_Artist (
	Genre_Artist_ID SERIAL PRIMARY KEY,
	Genre_ID INTEGER REFERENCES Genre(Genre_ID),
	Artist_ID INTEGER REFERENCES Artist(Artist_ID)
);
CREATE TABLE IF NOT EXISTS Artist_Album (
	Artist_Album_ID SERIAL PRIMARY KEY,
	Artist_ID INTEGER REFERENCES Artist(Artist_ID),
	Album_ID INTEGER REFERENCES Album(Album_ID)
);
CREATE TABLE IF NOT EXISTS Compilation_Track (
	Compilation_Track_ID SERIAL PRIMARY KEY,
	Compilation_ID INTEGER REFERENCES Compilation(Compilation_ID),
	Track_ID INTEGER REFERENCES Track(Track_ID)
);